Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,7 +23,7 @@ jobs:
       - name: Build React App
         run: |
           npm run build
-          ls -la ./build || echo "❌ Build folder is missing!"
+          ls -la ./build || echo "❌ Build folder is missing!" 
 
       - name: Debug GitHub Runner Storage
         run: df -h  # Check if storage is full
